name: Deploy docs

on:
  push:
    branches:
      - main
      - docs

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Build HTML
        uses: ammaraskar/sphinx-action@8.2.3
        with:
          docs-folder: docs
      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v4
        if: "github.ref == 'refs/heads/docs'"  # TODO change to main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          publish_branch: docs-build
